services:
  # Backend service
  - type: web
    name: buscador-estabelecimentos-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    repo: https://github.com/seu-usuario/buscador-estabelecimentos.git # Substitua pelo seu repositório
    branch: main
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: FIRECRAWL_API_URL
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: buscador-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend service
  - type: web
    name: buscador-estabelecimentos-frontend
    env: node
    buildCommand: cd frontend && pnpm install && pnpm build
    startCommand: cd frontend && pnpm preview
    repo: https://github.com/seu-usuario/buscador-estabelecimentos.git # Substitua pelo seu repositório
    branch: main
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: NODE_VERSION
        value: 20.18.0

databases:
  - name: buscador-db
    databaseName: buscador
    user: buscador_user
    plan: free
